train:
  standard:
    - name: flip
      params:
        p: 0.5
    - name: rotate
      params:
        limit: 10
        p: 0.3
    - name: color_jitter
      params:
        brightness: 0.2
        contrast: 0.2
        saturation: 0.2
        hue: 0.1
        p: 0.3
    - name: randombrightnesscontrast
      params:
        p: 0.2
  advanced:
    mosaic:
      enabled: false
      prob: 0.0
      output_size: 1024
    cutmix:
      enabled: false
      prob: 0.0
      alpha: 1.0
val:
  standard: []
resize_if_needed:
  enabled: true
  target_longest_side: 500
  tolerance: 0.1
